### ISSUE TITLE
error 400 , token locked or disabled

### ISSUE THREAD

**Issue by AwJHub** [V4NSH4J/discord-mass-DM-GO#20]
![Screenshot 2021-12-24 234438](https://user-images.githubusercontent.com/76947375/147371303-d1b898d5-093a-4cdc-ad87-a442c72bd648.png)

**Comment by AwJHub** [comment]
fixed, forgot to scrape

**Comment by JeremyMeissner** [comment]
Hi I have the same problem, what process fix your problem?
I scrape memberids and put them in the memberids.txt file but I still have the problem.
@AwJHub
